_commit: 0.5.2
_src_path: gh:georgedouzas/copier-pdm-nox
author_email: gdouzas@icloud.com
author_fullname: Georgios Douzas
author_username: georgedouzas
copyright_date: '2021'
copyright_holder: Georgios Douzas
copyright_holder_email: gdouzas@icloud.com
copyright_license: MIT License
project_description: A general interface for clustering based over-sampling algorithms.
python_package_distribution_name: cluster-over-sampling
python_package_import_name: clover
python_versions: '>=3.10, <3.12'
repository_name: cluster-over-sampling
repository_namespace: georgedouzas

