name: CI

on:
  push:
    branches:
      - master
      - development

jobs:

  checks:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        cache: true
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: pdm install --no-editable -G maintenance -G checks

    - name: Check the code quality
      run: pdm checks quality

    - name: Check if the code is correctly typed
      run: pdm checks types

  tests:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        cache: true
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: pdm install --no-editable -G maintenance -G tests

    - name: Run the test suite
      run: pdm tests
